%MATLAB Code from Sensor Array Analyzer App

%Generated by MATLAB 9.6 and Phased Array System Toolbox 4.1

%Generated on 19-Apr-2021 09:36:21

% Create a uniform rectangular array
h = phased.URA;
h.Size = [16 16];
h.ElementSpacing = [0.0025 0.0025];
h.Lattice = 'Rectangular';
h.ArrayNormal = 'x';
%Calculate Row Taper
sll = -50;
nbar = 4;
rwind = taylorwin(16, nbar, sll)';
rwind = repmat(rwind,16,1);
%Calculate Column Taper
sll = -50;
nbar = 4;
cwind = taylorwin(16, nbar, sll)';
cwind = repmat(cwind.',1,16);
%Calculate taper
wind = rwind.*cwind;
h.Taper = wind;
%Create Isotropic Antenna Element
el = phased.IsotropicAntennaElement;
h.Element = el;
%Assign steering angles, frequencies and propagation speed
SA = [0;0];
%Assign number of phase shift quantization bits
PSB = 16;
F = 60000000000;
PS = 300000000;
%Create figure, panel, and axes
fig = figure;
panel = uipanel('Parent',fig);
hAxes = axes('Parent',panel,'Color','none');
%Calculate Steering Weights
w = zeros(getNumElements(h), length(F));
SV = phased.SteeringVector('SensorArray',h, 'PropagationSpeed', PS, ...
    'NumPhaseShifterBits', PSB(1));
%Find the weights
for idx = 1:length(F)
    w(:, idx) = step(SV, F(idx), SA(:, idx));
end
%Plot 3d graph
fmt = 'polar';
pattern(h, F(1), 'PropagationSpeed', PS, 'Type','directivity', ...
    'CoordinateSystem', fmt,'weights', w(:,1));
%Adjust the view angles
view(hAxes,[152.396666573455 55.0772961732111]);
title = get(hAxes, 'title');
title_str = get(title, 'String');
%Modify the title
[Fval, ~, Fletter] = engunits(60000000000);
steeringString = 'steered at 0 Az, 0 El';
title_str = [title_str sprintf('\n') num2str(Fval) ' ' Fletter 'Hz ' ...
    steeringString];
set(title, 'String', title_str);
